### ISSUE TITLE
Sliders not functioning properly for keyboard nav

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/rutherford-scattering#123]
The controls in the Atom panel appear to have odd behavior under keyboard navigation.

- The proton slider becomes stuck if trying to use the shift + arrow keys. All other interactions appear normal

- The neutron slider will increase its value under normal arrow key operations but halt when trying to decrease the value. It also has the same shift behavior as the proton slider.

**Comment by jessegreenberg** [comment]
@mbarlow12 I think the problem is related to the default step sizes in HSlider and that  the sliders have custom endDrag functions that limit the values.  The default step sizes don't produce integer values in this sim so the endDrag listeners are rounding the value back to an integer value so they seem stuck. Could you please try changing the keyboardStep and shiftKeyboardStep for each slider?

**Comment by mbarlow12** [comment]
Can do @jessegreenberg. Do you think they should be arbitrary values or range based increments?

**Comment by jessegreenberg** [comment]
Hmm, not sure. Perhaps values that conform to the rounding applied in endDrag listeners? 
```js
countProperty.set( Util.roundSymmetric( countProperty.value ) );
```

Arbitrary integer values might accomplish that, but if they can be based on the ranges that would also  be nice.

**Comment by mbarlow12** [comment]
Set the steps as follows:
- Default: 5
- Shift: 1
- Page Up/Down: 10
