### ISSUE TITLE
Legend Tool Box Contents

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/rutherford-scattering#147]
@jessegreenberg 
For phetsims/QA/issues/181
Quick design question.  On the first screen in the atomic scale scene, should there be a spot in the legend for the actual alpha particles?  At the moment it just has the "particle trace"
![legend](https://user-images.githubusercontent.com/41024075/44882445-8dcae880-ac70-11e8-9078-050e7a891498.PNG)

**Comment by jessegreenberg** [comment]
Hmm, I don't think so because this is how it is in the deployed version, but good question @KatieWoe. @arouinfar what do you think about this?

**Comment by arouinfar** [comment]
@KatieWoe @jessegreenberg I took a look at the latest rc, and the legend is looking fine to me. In the atomic view, the alpha particles themselves aren't visible, just the trace, which is what's in the legend.

**Comment by jessegreenberg** [comment]
OK, thanks @arouinfar. Ill go ahead and close this issue.

**Comment by arouinfar** [comment]
Ah, I think see @KatieWoe's point, though. The purple dots represent the alpha particles, and the trace isn't always visible, so it is slightly odd that the trace is in the legend.

My guess is that the design team wanted to avoid having two different legend entries for alpha particles, which could cause confusion.  I took a look at the interview notes, and didn't see anything about the alpha particle trace legend entry, so my guess is that it wasn't an issue. I still think we can leave things as-is, so that's for closing @jessegreenberg.
