### ISSUE TITLE
Add an entry for the scale text English string

### ISSUE THREAD

**Issue by samreid** [phetsims/rutherford-scattering#2]
To get the sim to run after recent changes to internationalization, I had to add this line to the english string file:

```js
  "rutherfordAtom.scale": {
    "value": "??????? What is this text supposed to be????"
  }
```

Wasn't sure exactly what that text should be.

**Comment by samreid** [comment]
I added the above text as placeholder text, so the sim will still launch.  However, @thejakey should add the appropriate text into the file.

**Comment by thejakey** [comment]
In the Java format, the string is a template and the units are inserted from a numerical value. JavaScript doesn't have string building facilities (yet), but the behavior can be mimicked with *string.replace()* and the like. I will fix this soon, using the aforementioned workaround, unless I am told to do it otherwise.

**Comment by thejakey** [comment]
By yet, I mean ecmascript 6 does.

**Comment by samreid** [comment]
OK perfect, thanks!

**Comment by thejakey** [comment]
Fixes are in, not sure why the way strings are dealt with changed (from `stringfile.json` to `strings/stringfile.json`) but it does make more sense this way and I have updated how the project gets strings.

**Comment by ariel-phet** [comment]
I am guessing this is no longer an issue since Jake's work was removed, closing
