### ISSUE TITLE
Old sim docs

### ISSUE THREAD

**Issue by schmitzware** [phetsims/rutherford-scattering#29]
There's several documents in the old java simulation doc directory. I've moved these over to the new sim but wanted to check if this is correct.

rutherford-scattering.pdf - looks like slides for a presentation
trajectories.pdf - the math for the Rutherford  model
TipsForTeachers-RutherfordScattering.docx - teacher notes

**Comment by pixelzoom** [comment]
rutherford-scattering.pdf is the design doc for the Java version. This is from back in the days when design docs were a bit more primitive and less standardized.

trajectories.pdf is probably worth keeping. It can be referenced in doc/model.txt.

I suspect that the tips for teachers lives elsewhere. Unless this is the copy that has been (and will be) edited/revised, it should be deleted.

**Comment by pixelzoom** [comment]
rutherford-scattering.pdf is the design doc for the Java version. This is from back in the days when design docs were a bit more primitive and less standardized. I would delete it, since it doesn't match the HTML5 version.

trajectories.pdf is probably worth keeping. It can be referenced in doc/model.txt.

I suspect that the tips for teachers lives elsewhere. Unless this is the copy that has been (and will be) edited/revised, it should be deleted.

**Comment by pixelzoom** [comment]
Btw... Back in the Java/Flash days, after we moved to Google Docs for design docs, we had a policy of checking a PDF of the design doc into SVN.  That typically led to the PDF getting stale. So I don't recommend doing that for HTML5 sims, unless there's a desire to make the design doc publicly available.

**Comment by ariel-phet** [comment]
@schmitzware 

definitely should not be in the github repo
- rutherford-scattering.pdf - looks like slides for a presentation
- TipsForTeachers-RutherfordScattering.docx - teacher notes


trajectory seems fine to put in the repo

**Comment by schmitzware** [comment]
Thanks.  I'll keep the trajectory PDF and delete the others.
