### ISSUE TITLE
refine look of nucleus in the Rutherford Atom screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#59]
@ariel-phet asked to create this issue in 3/10/16 dev meeting.

Requests are:

(1) Refine the look of the nucleus in the Rutherford Atom screen, so that it looks more spherical and doesn't contain holes.  Either use the approach in build-an-atom, or have @andrewadare come up with something else.  If something else, consider apply it to build-an-atom (create an issue).

(2) Programmatically generate the icon for the Rutherford Atom screen, so that the look is the same. Jettison the related .png and .ai files.

**Comment by pixelzoom** [comment]
@schmitzware This is not something that you need to do. It will likely be done by @jessegreenberg or @andrewadare.

**Comment by jessegreenberg** [comment]
@ariel-phet is this something that you would like @jessegreenberg and/or @andrewadare to work on now?  As mentioned in https://github.com/phetsims/rutherford-scattering/issues/59#issue-139980432 we could either generalize the approach used by build-an-atom and isotopes-and-atomic-mass (hopefully already in shred) or @andrewadare could work on a new representation, which could replace the one in shred.

**Comment by ariel-phet** [comment]
@jessegreenberg it seems like it is worth investigating generalizing the approach used in build-an-atom. It just needs to "look" reasonable, but I would advice consulting with @andrewadare to makes sure that the reasonable look does not break any major rules of nuclear physics!

**Comment by jessegreenberg** [comment]
Sounds good @ariel-phet, thanks.  I will consult with @andrewadare before proceeding.

**Comment by jessegreenberg** [comment]
@andrewadare and I discussed the representation and some possible alternatives.  One possibility that @andrewadare suggested was to use the Woods-Saxon formula to model the density distribution of nucleons as a function of the radius.
![density](https://cloud.githubusercontent.com/assets/6396244/15833248/2e55cb1e-2be3-11e6-8b4f-701e4a5f2061.jpg)
( http://slideplayer.com/slide/8620364/ )

The result might look like this Glauber Monte Carlo model, but with a single nucleus.
![glauber monte carlo nucleus](https://cloud.githubusercontent.com/assets/6396244/15833327/7d45c120-2be3-11e6-9cb2-eda4e8c5ebe9.png)
(http://entropybound.blogspot.com/2008/05/phobos-glauber-monte-carlo.html)

Not sure if this would have implications for the 'unstable' animations in isotopes-and-atomic-mass and build-an-atom.

@ariel-phet for now I will use the algorithm in shred as it is, since it isn't fundamentally rule breaking.  I am not sure if the representation shown in the Glauber Monte Carlo model would be desirable or important for the learning goals of sims that use shred.

**Comment by jessegreenberg** [comment]
Looking pretty good:
![capture](https://cloud.githubusercontent.com/assets/6396244/15915921/ad56fafa-2daa-11e6-9f6a-2827727840cc.PNG)

But I had to make some changes in shred and I would like to ask a couple of questions about ParticleAtom.js before making the commit.

**Comment by jessegreenberg** [comment]
If we go through with this new representation, we will need to also replace icons for 
- [ ] the Rutherford Nucleus Scene radio button
- [ ] the Rutherford Nucleus Screen icon

**Comment by ariel-phet** [comment]
The screenshot looks quite good to me!

**Comment by jessegreenberg** [comment]
Home screen icon and radio button icon both match the new nucleus representation.

**Comment by jessegreenberg** [comment]
I think that completes this issue, ready for review.

**Comment by jessegreenberg** [comment]
This was verified, closing.
