### ISSUE TITLE
Alpha particles overlap with atom

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rutherford-scattering#63]
@amyh-phet @ariel-phet setting the sim to minimum protons, maximum neutrons, and max energy can cause some alpha particles to visually overlap with the atom. Is this going to hinder student learning?
![alphacuddle](https://cloud.githubusercontent.com/assets/5863899/14156899/f5717560-f685-11e5-8c99-76d3cab6d656.PNG)
The shape of the atom is random every time, so some shapes have a more extreme overlap than the screenshot I have. 
Seen in all Win 10 browsers. For phetsims/tasks/issues/545.

**Comment by ariel-phet** [comment]
Definitely a question for @amyh-phet

**Comment by amyh-phet** [comment]
@phet-steele and @ariel-phet  While overlap looks a bit odd, I don't see a way around this with the current model used for the sim.  The overlap is caused by a small impact parameter due to the small number of protons in nucleus and the large energy of the incoming alpha particles.  This behavior would support students achieving the second learning goal, "For charged nucleus, describe qualitatively how angle of deflection depends on: Energy of incoming particle, Impact parameter, Charge of target".   Same behavior existed in Java sim.
